// <auto-generated />
namespace EzPOS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddwarrantyandunitforProductrequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddwarrantyandunitforProductrequired));
        
        string IMigrationMetadata.Id
        {
            get { return "202209070651137_Add warranty and unit for Product required"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
